import type { FoodProfile } from "./types";

export const FOODS: FoodProfile[] = [
  {
    id: "samosa",
    name: "Samosa",
    slug: "samosa",
    image: "/foods/samosa.webp?v=webp3",
    originFlag: "🇮🇳",
    originLabel: "From India",
    tagline: "Two chutneys, extra drama, will show up hot and crispy",
    personality: ["Desi", "Reliable", "Slightly dramatic", "Social butterfly"],
    bio: "I come with two sides: chutney. Don’t ask me to choose.",
    greenFlag: "Will show up hot, crispy and ready to commit.",
    redFlag: "Emotionally unavailable after 6 PM.",
    loveLanguage: "Sharing — but only if you ask nicely.",
    isPrimary: true
  },
  {
    id: "brownie",
    name: "Brownie",
    slug: "brownie",
    image: "/foods/brownie.webp?v=webp3",
    originFlag: "🇺🇸",
    originLabel: "From USA",
    tagline: "Long walks to the fridge at midnight, being fudgy not cakey, ice cream on top energy",
    personality: ["Sweet", "Comforting", "Flirty", "Low maintenance"],
    bio: "I’m basically a hug, but with chocolate.",
    greenFlag: "Makes bad days significantly better.",
    redFlag: "Has a serious “just one bite” trust issue.",
    loveLanguage: "Acts of sweetness.",
    isPrimary: true
  },
  {
    id: "protein-bar",
    name: "Protein Bar",
    slug: "protein-bar",
    image: "/foods/protein-bar.webp?v=webp3",
    originFlag: "🇺🇸",
    originLabel: "From USA",
    tagline: "Macros over cake, 5am alarms, will mention protein on date one",
    personality: ["Disciplined", "Ambitious", "Gym-coded", "Slightly judgmental"],
    bio: "You had cake. I had macros. We are not the same.",
    greenFlag: "Will motivate you to become your best self.",
    redFlag: "May bring up protein intake on the first date.",
    loveLanguage: "Consistency.",
    isPrimary: true
  },
  {
    id: "nacho-cheese",
    name: "Nacho + Cheese Dip",
    slug: "nacho-cheese",
    image: "/foods/nacho-cheese.webp?v=webp3",
    originFlag: "🇲🇽",
    originLabel: "From Mexico",
    tagline: "Party starter, zero personal space, the cheese stays with me",
    personality: ["Fun", "Chaotic", "Affectionate", "Very clingy"],
    bio: "You can have the nacho. But the cheese stays with me.",
    greenFlag: "Always brings the party.",
    redFlag: "Zero concept of personal space.",
    loveLanguage: "Physical touch. Mostly dipping.",
    isPrimary: true
  },
  {
    id: "gulab-jamun",
    name: "Gulab Jamun",
    slug: "gulab-jamun",
    image: "/foods/gulab-jamun.webp?v=webp3",
    originFlag: "🇮🇳",
    originLabel: "From India",
    tagline: "Mummy already likes me, extra sugar, every shaadi playlist",
    personality: ["Traditional", "Romantic", "Sweet", "Family-approved"],
    bio: "Mummy already likes me.",
    greenFlag: "Excellent with commitment and celebrations.",
    redFlag: "Gets emotionally involved with every shaadi.",
    loveLanguage: "Words of affirmation + extra sugar.",
    isPrimary: true
  },
  {
    id: "tiramisu",
    name: "Tiramisu",
    slug: "tiramisu",
    image: "/foods/tiramisu.webp?v=webp3",
    originFlag: "🇮🇹",
    originLabel: "From Italy",
    tagline: "I have layers, please say my name right, espresso after dark",
    personality: ["Sophisticated", "Mysterious", "International", "A little pretentious"],
    bio: "I have layers. Please pronounce my name correctly.",
    greenFlag: "Elegant, complex and surprisingly comforting.",
    redFlag: "Will judge your dessert vocabulary.",
    loveLanguage: "Quality time.",
    isPrimary: true
  },
  {
    id: "broccoli",
    name: "Broccoli",
    slug: "broccoli",
    image: "/foods/broccoli.webp?v=webp3",
    originFlag: "🇮🇹",
    originLabel: "From Italy",
    tagline: "Vitamins, birthday-party trauma, still asking for a chance",
    personality: ["Responsible", "Healthy", "Mature", "Trying very hard"],
    bio: "I know what you're thinking. Give me a chance.",
    greenFlag: "Will always have your back... and your vitamins.",
    redFlag: "Has been rejected at birthday parties since childhood.",
    loveLanguage: "Acts of service.",
    isPrimary: false
  },
  {
    id: "bhole-chature",
    name: "Bhole Chature",
    slug: "bhole-chature",
    image: "/foods/bhole-chature.webp?v=webp3",
    originFlag: "🇮🇳",
    originLabel: "From India",
    tagline: "Chaotic good, extra masala, will talk to everyone in the line",
    personality: ["Loud", "Dramatic", "Attention-seeking", "Passionate"],
    bio: "I don't enter a room. I make an entrance.",
    greenFlag: "Brings excitement wherever it goes.",
    redFlag: "Cannot communicate without making noise.",
    loveLanguage: "Grand gestures.",
    isPrimary: false
  },
  {
    id: "pizza",
    name: "Pizza",
    slug: "pizza",
    image: "/foods/pizza.webp?v=webp3",
    originFlag: "🇮🇹",
    originLabel: "From Italy",
    tagline: "Everybody’s type eventually, never share the last slice",
    personality: ["Popular", "Easy-going", "Adaptable", "Slightly basic"],
    bio: "Everybody says I'm not their type. Then orders me anyway.",
    greenFlag: "Works for almost every situation.",
    redFlag: "Has too many exes.",
    loveLanguage: "Sharing — but not the last slice.",
    isPrimary: false
  },
  {
    id: "sushi",
    name: "Sushi",
    slug: "sushi",
    image: "/foods/sushi.webp?v=webp3",
    originFlag: "🇯🇵",
    originLabel: "From Japan",
    tagline: "Raw honesty, wasabi optional, slightly expensive first date",
    personality: ["Adventurous", "Stylish", "Sophisticated", "Risk-taking"],
    bio: "Raw honesty. Zero drama. Wasabi optional.",
    greenFlag: "Will take you out of your comfort zone.",
    redFlag: "May cost more than your first date.",
    loveLanguage: "New experiences.",
    isPrimary: false
  }
];

export const FOOD_BY_ID = Object.fromEntries(FOODS.map((f) => [f.id, f]));
export const PRIMARY_FOODS = FOODS.filter((f) => f.isPrimary);
